# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('radius', models.IntegerField(default=5, verbose_name='Radio')),
                ('message', models.CharField(max_length=200, verbose_name='Mensaje')),
            ],
        ),
    ]
